### ISSUE TITLE
ZynqRobotController updates for DHB-10 Motor Controller

### ISSUE THREAD

**Issue by TJLW** [smartsystemslab-uf/ROS-ArloRobot#6]
As a group task, I'd like some students to get familiar with the system by actually implementing some changes needed to get the DHB-10 Motor Controller working with the ZynqRobotController system and DHB10 Controller ROS node.

The source code for the node is in [motor-controller-interface.py](https://github.com/smartsystemslab-uf/ROS-ArloRobot/blob/master/dhb10-controller/scripts/motor-controller-interface.py).

**TO DO**

- [ ] Create a catkin workspace on the Zybo and clone this repo into the /src directory of your workspace. 

- [ ] Dive into the ROS modules for the Arlo. There are a few different functionalities made available that will help us interact with the robot with ROS. 

- [ ] Analyze and understand motor-controller-interface.py of the DHB-10 Controller node. What topics does it subscribe to? Publishing topics? What does it do? Ask questions!

- [ ]  Wire Zybo to Arlo Robot according to [Initial Wiring for Arlo](https://github.com/smartsystemslab-uf/ZynqRobotController/tree/master/FPGA/Zynq_Robot_Controller_v2#initial-wiring-for-arlo-robot).

- [ ] The node currently relies on a relay to be integrated to the robot, which the robots in the lab do not yet have. Modify the code such that a ROS parameter can be provided to remove the need for a relay. See issue #7.

- [ ] Without a relay, the motor controller should work but needs to be tested. This will require some way to send the expected messages to the controller. There are many teleoperation ROS nodes out there that will do this. [This is a classic](http://wiki.ros.org/teleop_twist_keyboard).

- [ ] Drive the robot around! Note that without a relay currently implemented on the robots, its is almost guaranteed the DHB-10 motor controller (the actual board) is going to get an error and require it to be reset. This can be done by simply toggling the Arlo Motor power switch. These may answer some questions about what the code is doing when speaking to the motor controller: [Motor Controller Product Guide](https://www.parallax.com/sites/default/files/downloads/28231-DHB-10-Motor-Controller-Guide-v1.0.pdf) and [Motor Controller Firmware Guide](https://www.parallax.com/sites/default/files/downloads/28231-DHB-10-Arlo-Firmware-Guide-v1.0.pdf).

- [ ] The motor controller ROS node currently uses two separate serial ports with one dedicated to reading and writing. This is sub-optimal and should be consolidated to a single port for both reading and writing. See issue #8.

- [ ] Pull out the relay functionality of the dhb-10 controller node and create a separate relay_control node that uses GPIO to control a relay. The controller node should maintain the parameter that allows toggling automatic error reset. See issue #9.
